### ISSUE TITLE
thprac doesn't actually apply vpatch to pcb when you run pcb through the launcher and check "use vpatch"

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#53] opened 2022-06-14 09:37 UTC
you still get 59.something fps and lots of input lag
you can compare it with launching vpatch.exe *first*, then injecting thprac

**Comment by 32th-System** [comment] 2022-06-14 15:00
Are you still able to change window size?

**Comment by toimine** [comment] 2022-06-14 16:15
lemme check

**Comment by toimine** [comment] 2022-06-14 16:17
in pcb no

**Comment by 32th-System** [comment] 2022-06-15 10:27
This is very strange because I wasn't able to replicate this.  On an unrelated note: does thcrap work with vpatch for you?

**Comment by toimine** [comment] 2022-06-15 20:13
I haven't tried it, I'll send you my game tomorrow

**Comment by 32th-System** [comment] 2022-06-18 10:16
So, you told me that the issue resolved itself on Discord. Do you want to close this issue?

**Comment by toimine** [comment] 2022-06-20 03:53
Yes

**Comment by hoangcaominh** [comment] 2022-06-20 04:27
I forgot to mention, thprac v1 does successfully apply vpatch as opposed to v2 and later. The difference is noticable.

**Comment by toimine** [comment] 2022-06-20 04:28
Ooh somebody else has the glitch now??? 👀

**Comment by hoangcaominh** [comment] 2022-06-20 04:32
I have been practicing PCB with thprac v1.9.4.2 because that one works with vpatch.
Not sure what shenanigans ack did in his v2 but I can there's still input delay.

**Comment by 32th-System** [comment] 2022-06-20 06:51
But can you change the window size?

**Comment by 32th-System** [comment] 2022-06-20 07:42
It can change window size, that's how I determine if vpatch is applied. But if you get input lag but can change the window size then I can't help you

**Comment by hoangcaominh** [comment] 2022-06-20 07:50
If you're talking about the config in the ini file then yes, v2 can change the window size.

**Comment by 32th-System** [comment] 2022-06-20 08:03
Yeah, if vpatch seemingly doesn't get applied, can you use vpatch.ini to change window size?

**Comment by hoangcaominh** [comment] 2022-06-20 08:06
Apparently yes.
I can slowdown the replay too.

**Comment by 32th-System** [comment] 2022-07-07 10:39
Then vpatch got applied. Do you still get input lag?

**Comment by hoangcaominh** [comment] 2022-07-07 18:48
Yes unfortunately

**Comment by hoangcaominh** [comment] 2022-07-07 19:52
Now that you mentioned it, I forgot to test the "apply thprac on ongoing game" option the whole time and only did it just now.
This option applies vpatch properly, as in it also removes input lag unlike the apply & start game option.

**Comment by 32th-System** [comment] 2022-07-07 20:24
ticking the apply box and starting the game does the same thing that vpatch.exe does. In any case, if what you're saying is true then the issue still stands. It might also be a placebo effect, I have no way of knowing

**Comment by 32th-System** [comment] 2022-07-19 20:44
I think I found the cause. Having "Unlock monitor refresh rate" enabled. What that feature does is letting your monitor maintain it's full refresh rate while still running the game at 60 fps. This has absolutely no effect and according to my investigations causes this issue. I have removed it so I guess I can close this

**Closed** 2023-03-30 16:41 UTC
Labels: bug
